el_clients:
  - geth
cl_clients:
  - lighthouse
network_params:
  chain_name: "my-pos-chain"
  chain_id: 2025
  seconds_per_slot: 12
  total_terminal_difficulty: "0x1"
  num_validators: 8
  min_genesis_time: 1710000000
